language: java
jdk:
  - openjdk8
sudo: false
addons:
  apt:
    packages:
      - openjdk-8-jre-headless
script:
  - mvn test -B -Djava.awt.headless=true
after_success:
  - java main.MakeDocumentation
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/
  on:
    branch: master
